from PyENCRYPTO_utils.typedefs import *

# #define AES_KEY_BITS			128
# #define AES_KEY_BYTES			16
# #define AES_BITS				128
# #define AES_BYTES				16

AES_KEY_BITS = 128
AES_KEY_BYTES = 16
AES_BITS = 128
AES_BYTES = 16

# #define SHA1_OUT_BYTES 20
# #define SHA256_OUT_BYTES 32
# #define SHA512_OUT_BYTES 64
#
# #define MAX_NUM_COMM_CHANNELS 256
# #define ADMIN_CHANNEL MAX_NUM_COMM_CHANNELS-1

SHA1_OUT_BYTES = 20
SHA256_OUT_BYTES = 32
SHA512_OUT_BYTES = 64

MAX_NUM_COMM_CHANNELS = 256 # 通信通道的最大数量
ADMIN_CHANNEL = MAX_NUM_COMM_CHANNELS - 1   # 管理员通道

